package server

import "net/http"

type mcpToolCallHandler func(*handler, http.ResponseWriter, *http.Request, string, map[string]any) (any, bool, error)

var mcpToolCallHandlers = map[string]mcpToolCallHandler{
	"recall":                      (*handler).mcpRecallToolCall,
	"ingest_document":             (*handler).mcpIngestDocumentToolCall,
	"ingest_documents":            (*handler).mcpIngestDocumentsToolCall,
	"remember_claim":              (*handler).mcpRememberClaimToolCall,
	"capture_observation":         (*handler).mcpCaptureObservationToolCall,
	"capture_task_outcome":        (*handler).mcpCaptureTaskOutcomeToolCall,
	"list_observations":           (*handler).mcpListObservationsToolCall,
	"challenge":                   (*handler).mcpChallengeToolCall,
	"forget":                      (*handler).mcpForgetToolCall,
	"discover_scopes":             (*handler).mcpDiscoverScopesToolCall,
	"rebuild_summaries":           (*handler).mcpRebuildSummariesToolCall,
	"policy_plan":                 (*handler).mcpPolicyPlanToolCall,
	"working_memory_compose":      (*handler).mcpWorkingMemoryComposeToolCall,
	"list_conflicts":              (*handler).mcpListConflictsToolCall,
	"resolve_conflict":            (*handler).mcpResolveConflictToolCall,
	"upsert_acl_policy":           (*handler).mcpUpsertAclPolicyToolCall,
	"list_acl_policies":           (*handler).mcpListAclPoliciesToolCall,
	"acl_decision":                (*handler).mcpAclDecisionToolCall,
	"upsert_agent_policy":         (*handler).mcpUpsertAgentPolicyToolCall,
	"list_agent_policies":         (*handler).mcpListAgentPoliciesToolCall,
	"agent_policy_decision":       (*handler).mcpAgentPolicyDecisionToolCall,
	"upsert_agent_profile":        (*handler).mcpUpsertAgentProfileToolCall,
	"list_agent_profiles":         (*handler).mcpListAgentProfilesToolCall,
	"upsert_source_config":        (*handler).mcpUpsertSourceConfigToolCall,
	"upsert_connector_source":     (*handler).mcpUpsertSourceConfigToolCall,
	"validate_mcp_source":         (*handler).mcpValidateMcpSourceToolCall,
	"validate_connector_source":   (*handler).mcpValidateMcpSourceToolCall,
	"inspect_connector_source":    (*handler).mcpInspectConnectorSourceToolCall,
	"list_source_configs":         (*handler).mcpListSourceConfigsToolCall,
	"list_connector_sources":      (*handler).mcpListSourceConfigsToolCall,
	"get_source_config":           (*handler).mcpGetSourceConfigToolCall,
	"get_connector_source":        (*handler).mcpGetSourceConfigToolCall,
	"set_source_config_status":    (*handler).mcpSetSourceConfigStatusToolCall,
	"set_connector_source_status": (*handler).mcpSetSourceConfigStatusToolCall,
	"enqueue_ingestion_job":       (*handler).mcpEnqueueIngestionJobToolCall,
	"sync_connector_source":       (*handler).mcpEnqueueIngestionJobToolCall,
	"list_ingestion_jobs":         (*handler).mcpListIngestionJobsToolCall,
	"retry_ingestion_job":         (*handler).mcpRetryIngestionJobToolCall,
	"cancel_ingestion_job":        (*handler).mcpCancelIngestionJobToolCall,
	"propose_learning":            (*handler).mcpProposeLearningToolCall,
	"list_learning_proposals":     (*handler).mcpListLearningProposalsToolCall,
	"decide_learning_proposal":    (*handler).mcpDecideLearningProposalToolCall,
	"apply_learning_proposal":     (*handler).mcpApplyLearningProposalToolCall,
	"request_approval":            (*handler).mcpRequestApprovalToolCall,
	"brain_anchor_backfill":       (*handler).mcpBrainToolCall,
	"brain_core_memory":           (*handler).mcpBrainToolCall,
	"brain_entity_dossier":        (*handler).mcpBrainToolCall,
	"brain_eval_history":          (*handler).mcpBrainToolCall,
	"brain_eval_record":           (*handler).mcpBrainToolCall,
	"brain_explain":               (*handler).mcpBrainToolCall,
	"brain_maintain":              (*handler).mcpBrainToolCall,
	"brain_memory_edit_proposal":  (*handler).mcpBrainToolCall,
	"brain_review":                (*handler).mcpBrainToolCall,
	"brain_scorecard":             (*handler).mcpBrainToolCall,
	"brain_shared_memory":         (*handler).mcpBrainToolCall,
	"brain_sources":               (*handler).mcpBrainToolCall,
	"brain_summaries":             (*handler).mcpBrainToolCall,
	"brain_think":                 (*handler).mcpBrainToolCall,
	"memory_health":               (*handler).mcpBrainToolCall,
}
