package server

import (
	memory "github.com/hermawan22/abra/internal/memory"
)

func mcpTools() []map[string]any {
	return []map[string]any{
		{
			"name":        "recall",
			"description": "Recall source-cited claims and supporting documents from Abra.",
			"inputSchema": map[string]any{
				"type":       "object",
				"required":   []string{"query", "scope"},
				"properties": map[string]any{"query": map[string]any{"type": "string"}, "scope": map[string]any{"type": "string"}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 20}, "include_unverified": map[string]any{"type": "boolean"}},
			},
		},
		{
			"name":        "ingest_document",
			"description": "Ingest one normalized source document into Abra. Requires write access to the document scope.",
			"inputSchema": objectSchema([]string{"source_type", "source_url", "title", "scope", "content"}, documentSchemaProperties()),
		},
		{
			"name":        "ingest_documents",
			"description": "Ingest a normalized batch of up to 50 source documents into Abra. Top-level scope/source_type/authority/metadata may be used as defaults. Defaults to fail-fast; set continue_on_error to return per-document status for ingest failures.",
			"inputSchema": objectSchema([]string{"documents"}, map[string]any{
				"scope":             stringSchema(),
				"source_type":       stringSchema(),
				"authority":         stringSchema(),
				"authority_score":   map[string]any{"type": "number", "minimum": 0, "maximum": 1},
				"approval_id":       stringSchema(),
				"metadata":          map[string]any{"type": "object"},
				"source_updated_at": stringSchema(),
				"continue_on_error": map[string]any{"type": "boolean"},
				"documents": map[string]any{
					"type":     "array",
					"minItems": 1,
					"maxItems": 50,
					"items":    objectSchema([]string{"source_url", "title", "content"}, documentSchemaProperties()),
				},
			}),
		},
		{
			"name":        "remember_claim",
			"description": "Store a claim. Claims without source_url are unverified by default.",
			"inputSchema": objectSchema([]string{"claim", "scope"}, map[string]any{
				"claim":               stringSchema(),
				"scope":               stringSchema(),
				"source_url":          stringSchema(),
				"source_type":         stringSchema(),
				"authority":           stringSchema(),
				"valid_from":          stringSchema(),
				"expires_at":          stringSchema(),
				"supersedes_claim_id": stringSchema(),
				"created_by":          stringSchema(),
				"approval_id":         stringSchema(),
				"metadata":            map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "capture_observation",
			"description": "Capture raw episodic or procedural memory without promoting it to a trusted claim. Requires write access and agent-write approval when enforcement is enabled.",
			"inputSchema": objectSchema([]string{"scope", "observation_text"}, map[string]any{
				"scope":             stringSchema(),
				"observation_text":  stringSchema(),
				"observation_type":  stringSchema(),
				"status":            map[string]any{"type": "string", "enum": []string{"raw", "proposed", "accepted", "rejected", "challenged", "deprecated", "expired"}},
				"authority":         stringSchema(),
				"authority_score":   map[string]any{"type": "number", "minimum": 0, "maximum": 1},
				"confidence":        map[string]any{"type": "number", "minimum": 0, "maximum": 1},
				"freshness_status":  map[string]any{"type": "string", "enum": []string{"fresh", "stale", "expired", "unknown"}},
				"source_url":        stringSchema(),
				"source_type":       stringSchema(),
				"source_id":         stringSchema(),
				"observed_at":       stringSchema(),
				"valid_from":        stringSchema(),
				"expires_at":        stringSchema(),
				"created_by":        stringSchema(),
				"approval_id":       stringSchema(),
				"subject_entity_id": stringSchema(),
				"object_entity_id":  stringSchema(),
				"relation_id":       stringSchema(),
				"claim_id":          stringSchema(),
				"document_id":       stringSchema(),
				"chunk_id":          stringSchema(),
				"source_config_id":  stringSchema(),
				"ingestion_job_id":  stringSchema(),
				"value":             map[string]any{"type": "object"},
				"metadata":          map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "capture_task_outcome",
			"description": "Capture a bounded after-task outcome as a raw source-backed observation and audit event, then create reviewable learning proposals only for repeated local outcome patterns. Does not promote trusted claims.",
			"inputSchema": objectSchema([]string{"task", "scope"}, map[string]any{
				"task":          stringSchema(),
				"scope":         stringSchema(),
				"hook":          map[string]any{"type": "string", "enum": []string{"after_task"}},
				"agent":         stringSchema(),
				"outcome":       map[string]any{"type": "string", "enum": []string{"succeeded", "failed", "partial", "blocked", "unknown"}},
				"summary":       stringSchema(),
				"files_changed": map[string]any{"type": "array", "maxItems": memory.MaxTaskOutcomeFiles, "items": stringSchema()},
				"commands_run": map[string]any{
					"type":     "array",
					"maxItems": memory.MaxTaskOutcomeCommands,
					"items": objectSchema([]string{"command"}, map[string]any{
						"command":     stringSchema(),
						"status":      map[string]any{"type": "string", "enum": []string{"succeeded", "failed", "skipped", "unknown"}},
						"exit_code":   map[string]any{"type": "integer"},
						"duration_ms": map[string]any{"type": "integer", "minimum": 0},
					}),
				},
				"tests_result": map[string]any{
					"type": "object",
					"properties": map[string]any{
						"status":   map[string]any{"type": "string", "enum": []string{"passed", "failed", "skipped", "unknown"}},
						"summary":  stringSchema(),
						"commands": map[string]any{"type": "array", "maxItems": memory.MaxTaskOutcomeTestCommands, "items": stringSchema()},
					},
				},
				"missing_context": map[string]any{"type": "array", "maxItems": memory.MaxTaskOutcomeMissingContext, "items": stringSchema()},
				"memory_refs_used": map[string]any{
					"type":     "array",
					"maxItems": memory.MaxTaskOutcomeMemoryRefs,
					"items": objectSchema(nil, map[string]any{
						"ref":        stringSchema(),
						"kind":       stringSchema(),
						"id":         stringSchema(),
						"source_url": stringSchema(),
					}),
				},
				"completed_at": stringSchema(),
				"source_url":   stringSchema(),
				"created_by":   stringSchema(),
				"approval_id":  stringSchema(),
				"metadata":     map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "list_observations",
			"description": "List or search raw observations for a scope. Observations are not trusted claims unless promoted through review.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":            stringSchema(),
				"query":            stringSchema(),
				"observation_type": stringSchema(),
				"status":           stringSchema(),
				"since":            stringSchema(),
				"until":            stringSchema(),
				"limit":            map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "challenge",
			"description": "Challenge or correct an existing claim.",
			"inputSchema": objectSchema([]string{"claim_id", "reason"}, map[string]any{"claim_id": stringSchema(), "reason": stringSchema(), "source_url": stringSchema(), "created_by": stringSchema(), "approval_id": stringSchema(), "conflicting_claim_id": stringSchema(), "severity": map[string]any{"type": "string", "enum": []string{"low", "medium", "high", "blocking"}}, "verdict": map[string]any{"type": "string", "enum": []string{"correct", "incorrect", "stale", "conflict", "useful", "not_useful"}}}),
		},
		{
			"name":        "forget",
			"description": "Deprecate a claim so it is no longer returned as trusted memory.",
			"inputSchema": objectSchema([]string{"claim_id"}, map[string]any{"claim_id": stringSchema(), "reason": stringSchema(), "created_by": stringSchema(), "approval_id": stringSchema()}),
		},
		{
			"name":        "brain_sources",
			"description": "Find supporting source chunks for a query.",
			"inputSchema": objectSchema([]string{"query", "scope"}, map[string]any{"query": stringSchema(), "scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 20}}),
		},
		{
			"name":        "brain_summaries",
			"description": "Find hierarchical memory summaries for a scope and query.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"query": stringSchema(), "scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 50}}),
		},
		{
			"name":        "brain_core_memory",
			"description": "List compact agent-visible core memory summaries for a scope. Read-only; returns core, agent_core, and optionally shared summary levels.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":          stringSchema(),
				"query":          stringSchema(),
				"agent":          stringSchema(),
				"include_shared": map[string]any{"type": "boolean"},
				"limit":          map[string]any{"type": "integer", "minimum": 1, "maximum": 50},
			}),
		},
		{
			"name":        "brain_shared_memory",
			"description": "List compact shared memory summaries for a scope. Read-only; use brain_memory_edit_proposal to suggest changes.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope": stringSchema(),
				"query": stringSchema(),
				"agent": stringSchema(),
				"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 50},
			}),
		},
		{
			"name":        "brain_memory_edit_proposal",
			"description": "Create a reviewable learning proposal to add, update, or remove a core, agent_core, or shared memory summary. Does not write trusted summary memory directly.",
			"inputSchema": objectSchema([]string{"scope", "level", "operation", "title", "rationale"}, map[string]any{
				"scope":            stringSchema(),
				"level":            map[string]any{"type": "string", "enum": []string{"core", "agent_core", "shared"}},
				"operation":        map[string]any{"type": "string", "enum": []string{"add", "update", "remove"}},
				"key":              stringSchema(),
				"summary_id":       stringSchema(),
				"title":            stringSchema(),
				"summary":          stringSchema(),
				"rationale":        stringSchema(),
				"source_url":       stringSchema(),
				"confidence":       map[string]any{"type": "number", "minimum": 0, "maximum": 1},
				"agent":            stringSchema(),
				"created_by":       stringSchema(),
				"dedupe":           map[string]any{"type": "boolean"},
				"evidence_refs":    map[string]any{"type": "array", "items": stringSchema(), "maxItems": 20},
				"replacement_text": stringSchema(),
				"metadata":         map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "brain_review",
			"description": "Review governed brain quality for a scope: memory health, weak anchors, stale claims, conflicts, learning cleanup, source freshness, and next actions. Read-only.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}}),
		},
		{
			"name":        "brain_scorecard",
			"description": "Return a compact governed brain scorecard for evidence, anchors, retrieval, freshness, conflicts, graph, learning, and eval readiness. Read-only and no LLM required.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}}),
		},
		{
			"name":        "brain_anchor_backfill",
			"description": "Find verified claims missing same-source quote/span anchors. Defaults to dry-run; set propose true and dry_run false to create reviewable learning proposals, not trusted memory writes.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}, "dry_run": map[string]any{"type": "boolean"}, "propose": map[string]any{"type": "boolean"}, "agent": stringSchema(), "created_by": stringSchema()}),
		},
		{
			"name":        "brain_maintain",
			"description": "Detect brain maintenance needs such as stale claims, weak anchors, conflicts, missing summaries, source refresh, and duplicate proposals. Defaults to dry-run; proposal mode never promotes trusted memory directly.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 200}, "dry_run": map[string]any{"type": "boolean"}, "propose": map[string]any{"type": "boolean"}, "agent": stringSchema(), "created_by": stringSchema()}),
		},
		{
			"name":        "brain_explain",
			"description": "Fetch a persisted why_trace by trace_id. Read-only; useful after brain_think or working-memory outputs include a trace id.",
			"inputSchema": objectSchema([]string{"trace_id"}, map[string]any{"trace_id": stringSchema()}),
		},
		{
			"name":        "brain_eval_record",
			"description": "Persist a brain eval run result for later audit. This records evaluation evidence only; it does not write trusted memory.",
			"inputSchema": objectSchema([]string{"scope", "total", "passed", "success", "reports"}, map[string]any{
				"scope":      stringSchema(),
				"suite_name": stringSchema(),
				"suite_file": stringSchema(),
				"agent":      stringSchema(),
				"total":      map[string]any{"type": "integer", "minimum": 1},
				"passed":     map[string]any{"type": "integer", "minimum": 0},
				"success":    map[string]any{"type": "boolean"},
				"reports":    map[string]any{"type": "array", "items": map[string]any{"type": "object"}},
				"metadata":   map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "brain_eval_history",
			"description": "List recent persisted brain eval runs for a scope. Read-only.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope": stringSchema(),
				"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 50},
			}),
		},
		{
			"name":        "brain_think",
			"description": "Return a governed brain answer with citations, gap analysis, entity dossiers, graph paths, temporal context, memory-health status, conflicts, verification, and an agent decision gate.",
			"inputSchema": objectSchema([]string{"question", "scope"}, map[string]any{
				"question":           stringSchema(),
				"scope":              stringSchema(),
				"agent":              stringSchema(),
				"entity":             stringSchema(),
				"mode":               map[string]any{"type": "string", "enum": []string{"fast", "balanced", "deep"}, "description": "Retrieval depth. Defaults to balanced. Fast caps fanout; deep expands evidence without enabling synthesis."},
				"as_of":              stringSchema(),
				"include_historical": map[string]any{"type": "boolean", "description": "Include labeled stale or historical context when available. Historical context is never autonomous truth."},
				"limit":              map[string]any{"type": "integer", "minimum": 1, "maximum": 20},
				"max_queries":        map[string]any{"type": "integer", "minimum": 1, "maximum": 12},
				"token_budget":       map[string]any{"type": "integer", "minimum": 300, "maximum": 12000},
				"include_unverified": map[string]any{"type": "boolean"},
				"synthesize":         map[string]any{"type": "boolean", "description": "Opt in to evidence-gated natural answer synthesis when the server has synthesis enabled. Defaults to deterministic governed output."},
			}),
		},
		{
			"name":        "brain_entity_dossier",
			"description": "Build a compact, cited, governance-aware dossier for one entity: active claims, relations, anchors, conflicts, temporal context, trust, and next action. Read-only and no LLM required.",
			"inputSchema": objectSchema([]string{"entity", "scope"}, map[string]any{
				"entity":             stringSchema(),
				"scope":              stringSchema(),
				"agent":              stringSchema(),
				"mode":               map[string]any{"type": "string", "enum": []string{"fast", "balanced", "deep"}, "description": "Retrieval depth. Defaults to balanced."},
				"as_of":              stringSchema(),
				"include_historical": map[string]any{"type": "boolean", "description": "Include labeled stale or historical context when available. Historical context is never autonomous truth."},
				"include_unverified": map[string]any{"type": "boolean"},
				"limit":              map[string]any{"type": "integer", "minimum": 1, "maximum": 20},
				"token_budget":       map[string]any{"type": "integer", "minimum": 300, "maximum": 12000},
			}),
		},
		{
			"name":        "memory_health",
			"description": "Return an aggregate health score and operational memory quality counts for a scope.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema()}),
		},
		{
			"name":        "discover_scopes",
			"description": "List memory scopes visible to the current API token with counts, so AI agents can choose the right scope before recall or working-memory composition. Pass expected_scope or query when the project scope is known or discovery is crowded.",
			"inputSchema": objectSchema(nil, map[string]any{
				"limit":          map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
				"query":          stringSchema(),
				"expected_scope": stringSchema(),
			}),
		},
		{
			"name":        "rebuild_summaries",
			"description": "Rebuild hierarchical memory summaries for existing documents in a scope. Requires a backfill approval when approval enforcement is enabled.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{"scope": stringSchema(), "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 10000}, "approval_id": stringSchema()}),
		},
		{
			"name":        "policy_plan",
			"description": "Plan which Abra recall queries an agent should run for a task hook.",
			"inputSchema": objectSchema([]string{"hook", "task", "scope"}, map[string]any{
				"hook":          map[string]any{"type": "string", "enum": []string{"before_task", "before_code", "after_task"}},
				"task":          stringSchema(),
				"scope":         stringSchema(),
				"files":         map[string]any{"type": "array", "items": stringSchema()},
				"changed_files": map[string]any{"type": "array", "items": stringSchema()},
				"language":      stringSchema(),
				"agent":         stringSchema(),
				"limit":         map[string]any{"type": "integer", "minimum": 1, "maximum": 20},
				"max_queries":   map[string]any{"type": "integer", "minimum": 1, "maximum": 10},
			}),
		},
		{
			"name":        "working_memory_compose",
			"description": "Compose a health-aware, source-backed working-memory packet for an agent task using policy planning, retrieval planning, recall, graph context, risks, evidence verification, memory health signals, decision gates, and next-step hints.",
			"inputSchema": objectSchema([]string{"task", "scope"}, map[string]any{
				"task":               stringSchema(),
				"scope":              stringSchema(),
				"hook":               map[string]any{"type": "string", "enum": []string{"before_task", "before_code", "after_task"}},
				"agent":              stringSchema(),
				"entity":             stringSchema(),
				"files":              map[string]any{"type": "array", "items": stringSchema()},
				"changed_files":      map[string]any{"type": "array", "items": stringSchema()},
				"language":           stringSchema(),
				"mode":               map[string]any{"type": "string", "enum": []string{"fast", "balanced", "deep"}, "description": "Retrieval depth. Defaults to balanced. Fast caps fanout; deep expands evidence without enabling synthesis."},
				"as_of":              stringSchema(),
				"include_historical": map[string]any{"type": "boolean", "description": "Include labeled stale or historical context when available. Historical context is never autonomous truth."},
				"limit":              map[string]any{"type": "integer", "minimum": 1, "maximum": 20},
				"max_queries":        map[string]any{"type": "integer", "minimum": 1, "maximum": 12},
				"token_budget":       map[string]any{"type": "integer", "minimum": 300, "maximum": 12000},
				"include_unverified": map[string]any{"type": "boolean"},
				"diagnostic":         map[string]any{"type": "boolean", "description": "Read-only compose for health checks; suppresses memory.composed audit events and learning proposal persistence."},
				"persist_learning":   map[string]any{"type": "boolean", "description": "Opt in to writing actionable learning suggestions as pending proposals. Requires write access and is ignored when diagnostic is true."},
			}),
		},
		{
			"name":        "list_conflicts",
			"description": "List claim or graph relation conflicts that may block autonomous agent work.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":       stringSchema(),
				"status":      map[string]any{"type": "string", "enum": []string{"open", "reviewing", "resolved", "suppressed"}},
				"severity":    map[string]any{"type": "string", "enum": []string{"low", "medium", "high", "blocking"}},
				"claim_id":    stringSchema(),
				"relation_id": stringSchema(),
				"limit":       map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "resolve_conflict",
			"description": "Resolve, suppress, reopen, or mark a claim conflict as reviewing. Requires ops access.",
			"inputSchema": objectSchema([]string{"conflict_id", "status"}, map[string]any{
				"conflict_id": stringSchema(),
				"status":      map[string]any{"type": "string", "enum": []string{"open", "reviewing", "resolved", "suppressed"}},
				"resolved_by": stringSchema(),
				"resolution":  stringSchema(),
				"metadata":    map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "upsert_acl_policy",
			"description": "Create or update a scoped ACL policy for identity gateways, connectors, and agent access overlays. Requires ops access and approval when enforcement is active.",
			"inputSchema": objectSchema([]string{"scope", "name", "subject_type", "subject_id", "effect", "rule"}, map[string]any{
				"scope":        stringSchema(),
				"name":         stringSchema(),
				"status":       map[string]any{"type": "string", "enum": []string{"active", "paused", "disabled", "deleted"}},
				"priority":     map[string]any{"type": "integer", "minimum": 1, "maximum": 1000},
				"subject_type": stringSchema(),
				"subject_id":   stringSchema(),
				"effect":       map[string]any{"type": "string", "enum": []string{"allow", "deny", "require_review"}},
				"rule":         map[string]any{"type": "object"},
				"created_by":   stringSchema(),
				"metadata":     map[string]any{"type": "object"},
				"approval_id":  stringSchema(),
			}),
		},
		{
			"name":        "list_acl_policies",
			"description": "List scoped ACL policies for an operator scope, optionally filtered by subject.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":        stringSchema(),
				"subject_type": stringSchema(),
				"subject_id":   stringSchema(),
				"limit":        map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "acl_decision",
			"description": "Evaluate scoped ACL policies for an identity gateway, connector, or agent principal.",
			"inputSchema": objectSchema([]string{"scope", "principal_type", "principal_id", "action"}, map[string]any{
				"scope":          stringSchema(),
				"principal_type": stringSchema(),
				"principal_id":   stringSchema(),
				"action":         stringSchema(),
				"resource_type":  stringSchema(),
				"resource_id":    stringSchema(),
				"context":        map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "upsert_agent_policy",
			"description": "Create or update a stored agent-action policy for autonomous agent gates. Requires ops access and approval when enforcement is active.",
			"inputSchema": objectSchema([]string{"scope", "name", "effect", "rule"}, map[string]any{
				"scope":        stringSchema(),
				"name":         stringSchema(),
				"status":       map[string]any{"type": "string", "enum": []string{"active", "paused", "disabled", "deleted"}},
				"priority":     map[string]any{"type": "integer", "minimum": 1, "maximum": 1000},
				"subject_type": stringSchema(),
				"subject_id":   stringSchema(),
				"effect":       map[string]any{"type": "string", "enum": []string{"allow", "deny", "require_review"}},
				"rule":         map[string]any{"type": "object"},
				"created_by":   stringSchema(),
				"metadata":     map[string]any{"type": "object"},
				"approval_id":  stringSchema(),
			}),
		},
		{
			"name":        "list_agent_policies",
			"description": "List stored agent-action policies for an operator scope.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope": stringSchema(),
				"limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "agent_policy_decision",
			"description": "Evaluate stored agent-action policies for a proposed risky agent action.",
			"inputSchema": objectSchema([]string{"scope", "action"}, map[string]any{
				"scope":          stringSchema(),
				"action":         stringSchema(),
				"target_type":    stringSchema(),
				"target_id":      stringSchema(),
				"principal_type": stringSchema(),
				"principal_id":   stringSchema(),
				"context":        map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "upsert_agent_profile",
			"description": "Create or update a configurable agent profile with default scope, allowed scopes, denied scopes, permissions, and memory preferences. Requires ops access and approval when enforcement is active.",
			"inputSchema": objectSchema([]string{"scope", "profile_key", "display_name"}, map[string]any{
				"scope":              stringSchema(),
				"profile_key":        stringSchema(),
				"display_name":       stringSchema(),
				"agent_type":         stringSchema(),
				"status":             map[string]any{"type": "string", "enum": []string{"active", "disabled", "deleted"}},
				"principal_ref":      stringSchema(),
				"default_scope":      stringSchema(),
				"allowed_scopes":     map[string]any{"type": "array", "items": stringSchema()},
				"denied_scopes":      map[string]any{"type": "array", "items": stringSchema()},
				"permissions":        map[string]any{"type": "object"},
				"memory_preferences": map[string]any{"type": "object"},
				"created_by":         stringSchema(),
				"metadata":           map[string]any{"type": "object"},
				"approval_id":        stringSchema(),
			}),
		},
		{
			"name":        "list_agent_profiles",
			"description": "List configurable agent profiles for an operator scope.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":  stringSchema(),
				"status": map[string]any{"type": "string", "enum": []string{"active", "disabled", "deleted"}},
				"limit":  map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "upsert_source_config",
			"description": "Create or update a source config for connector onboarding or scheduled ingestion. Core worker scheduling supports markdown, local_repo, git_repo, and mcp sources. Use source_type=mcp to onboard an HTTP MCP connector tool that returns normalized Abra documents; set connector_kind to the product or system name. Deployment overlays may store other source types and own their scheduling. Connector enablement and trusted authority changes may require approval when enforcement is active.",
			"inputSchema": sourceConfigSchema(),
		},
		{
			"name":        "upsert_connector_source",
			"description": "Connector-named alias for upsert_source_config. Create or update a connector-backed source config, usually with source_type=mcp, base_url, config.tool, connector_kind, authority, schedule_cron, and optional approval_id.",
			"inputSchema": sourceConfigSchema(),
		},
		{
			"name":        "validate_mcp_source",
			"description": "Dry-run a user-owned HTTP MCP connector/source tool and validate that it returns normalized Abra documents without creating a source config or queueing ingestion. Accepts base_url, mcp_url, or server_url plus tool, arguments, bearer_token_env, header_env, connector_kind, and document_source_type.",
			"inputSchema": validateMCPSourceSchema(),
		},
		{
			"name":        "validate_connector_source",
			"description": "Connector-named alias for validate_mcp_source. Use this before onboarding a connector to verify the HTTP MCP tool returns normalized Abra documents without saving config or queueing ingestion.",
			"inputSchema": validateMCPSourceSchema(),
		},
		{
			"name":        "inspect_connector_source",
			"description": "Inspect a user-owned HTTP MCP connector by calling upstream tools/list. Use this to discover export tool names before validating or registering the connector. Does not save config or queue ingestion.",
			"inputSchema": inspectConnectorSourceSchema(),
		},
		{
			"name":        "list_source_configs",
			"description": "List source configs and connector-backed sources for a scope.",
			"inputSchema": listSourceConfigsSchema(),
		},
		{
			"name":        "list_connector_sources",
			"description": "Connector-named alias for list_source_configs. List connector/source configs for a scope before inspecting, enabling, pausing, or syncing them.",
			"inputSchema": listSourceConfigsSchema(),
		},
		{
			"name":        "get_source_config",
			"description": "Read one source config by id, including status, authority, freshness policy, and latest success/error fields. Requires read access to the source scope.",
			"inputSchema": sourceConfigIDSchema(),
		},
		{
			"name":        "get_connector_source",
			"description": "Connector-named alias for get_source_config. Read one connector/source config by id, including status, authority, freshness policy, and latest success/error fields.",
			"inputSchema": sourceConfigIDSchema(),
		},
		{
			"name":        "set_source_config_status",
			"description": "Pause, resume, disable, or mark a source config status without rewriting connector config. Resuming to active is connector enablement and may require approval when enforcement is active.",
			"inputSchema": sourceConfigStatusSchema(),
		},
		{
			"name":        "set_connector_source_status",
			"description": "Connector-named alias for set_source_config_status. Enable, pause, disable, delete, or mark a connector/source config error without rewriting connector settings.",
			"inputSchema": sourceConfigStatusSchema(),
		},
		{
			"name":        "enqueue_ingestion_job",
			"description": "Queue an ingestion job for an active source config or connector. Requires write access to the source scope.",
			"inputSchema": enqueueIngestionJobSchema(),
		},
		{
			"name":        "sync_connector_source",
			"description": "Connector-named alias for enqueue_ingestion_job. Queue a manual, scheduled, webhook, backfill, or revalidation sync for an active connector/source config.",
			"inputSchema": enqueueIngestionJobSchema(),
		},
		{
			"name":        "list_ingestion_jobs",
			"description": "List ingestion jobs for a scope, optionally filtered by source config.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":            stringSchema(),
				"source_config_id": stringSchema(),
				"limit":            map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "retry_ingestion_job",
			"description": "Retry a failed or canceled ingestion job. Requires write access to the job scope.",
			"inputSchema": objectSchema([]string{"job_id"}, map[string]any{
				"job_id":       stringSchema(),
				"created_by":   stringSchema(),
				"max_attempts": map[string]any{"type": "integer", "minimum": 1, "maximum": 20},
				"metadata":     map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "cancel_ingestion_job",
			"description": "Cancel a queued or retrying ingestion job. Requires write access to the job scope.",
			"inputSchema": objectSchema([]string{"job_id"}, map[string]any{
				"job_id":     stringSchema(),
				"reason":     stringSchema(),
				"created_by": stringSchema(),
				"metadata":   map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "propose_learning",
			"description": "Create a reviewable learning proposal without promoting it to trusted memory.",
			"inputSchema": objectSchema([]string{"scope", "proposal_type", "title", "rationale"}, map[string]any{
				"scope":         stringSchema(),
				"proposal_type": map[string]any{"type": "string", "enum": []string{"claim", "challenge", "source_refresh", "summary_rebuild", "ingestion", "policy", "graph", "other"}},
				"title":         stringSchema(),
				"rationale":     stringSchema(),
				"target_type":   stringSchema(),
				"target_id":     stringSchema(),
				"source_url":    stringSchema(),
				"confidence":    map[string]any{"type": "number", "minimum": 0, "maximum": 1},
				"payload":       map[string]any{"type": "object"},
				"created_by":    stringSchema(),
				"approval_id":   stringSchema(),
			}),
		},
		{
			"name":        "list_learning_proposals",
			"description": "List reviewable learning proposals for a scope.",
			"inputSchema": objectSchema([]string{"scope"}, map[string]any{
				"scope":  stringSchema(),
				"status": map[string]any{"type": "string", "enum": []string{"pending", "accepted", "applying", "rejected", "applied", "canceled"}},
				"limit":  map[string]any{"type": "integer", "minimum": 1, "maximum": 100},
			}),
		},
		{
			"name":        "decide_learning_proposal",
			"description": "Accept, reject, or cancel a learning proposal. Accepted proposals return an apply_plan with the deterministic next operation; they are not auto-promoted to trusted memory.",
			"inputSchema": objectSchema([]string{"proposal_id", "status"}, map[string]any{
				"proposal_id":   stringSchema(),
				"status":        map[string]any{"type": "string", "enum": []string{"accepted", "rejected", "canceled"}},
				"reviewed_by":   stringSchema(),
				"review_reason": stringSchema(),
				"approval_id":   stringSchema(),
				"metadata":      map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "apply_learning_proposal",
			"description": "Apply an accepted learning proposal through Abra's first-party executor, then mark the proposal applied. Requires write access and any approval required by the apply plan.",
			"inputSchema": objectSchema([]string{"proposal_id"}, map[string]any{
				"proposal_id": stringSchema(),
				"applied_by":  stringSchema(),
				"approval_id": stringSchema(),
				"metadata":    map[string]any{"type": "object"},
			}),
		},
		{
			"name":        "request_approval",
			"description": "Create an operator approval request for risky agent writes or source changes.",
			"inputSchema": objectSchema([]string{"action", "scope", "reason"}, map[string]any{
				"action":       map[string]any{"type": "string", "enum": []string{"agent_write", "forget_claim", "challenge_claim", "source_authority_change", "scope_expansion", "backfill", "connector_enable", "acl_change", "other"}},
				"scope":        stringSchema(),
				"reason":       stringSchema(),
				"target_type":  stringSchema(),
				"target_id":    stringSchema(),
				"requested_by": stringSchema(),
				"expires_at":   stringSchema(),
				"payload":      map[string]any{"type": "object"},
				"metadata":     map[string]any{"type": "object"},
			}),
		},
	}
}

func mcpToolTraceName(name string) string {
	switch name {
	case "recall", "ingest_document", "ingest_documents", "remember_claim", "capture_observation", "capture_task_outcome", "list_observations", "challenge", "forget", "brain_sources", "brain_summaries", "brain_core_memory", "brain_shared_memory", "brain_memory_edit_proposal", "brain_review", "brain_scorecard", "brain_anchor_backfill", "brain_maintain", "brain_explain", "brain_eval_record", "brain_eval_history", "brain_think", "brain_entity_dossier", "memory_health", "discover_scopes", "rebuild_summaries", "policy_plan", "working_memory_compose", "list_conflicts", "resolve_conflict", "upsert_acl_policy", "list_acl_policies", "acl_decision", "upsert_agent_policy", "list_agent_policies", "agent_policy_decision", "upsert_agent_profile", "list_agent_profiles", "upsert_source_config", "upsert_connector_source", "validate_mcp_source", "validate_connector_source", "inspect_connector_source", "list_source_configs", "list_connector_sources", "get_source_config", "get_connector_source", "set_source_config_status", "set_connector_source_status", "enqueue_ingestion_job", "sync_connector_source", "list_ingestion_jobs", "retry_ingestion_job", "cancel_ingestion_job", "propose_learning", "list_learning_proposals", "decide_learning_proposal", "apply_learning_proposal", "request_approval":
		return name
	default:
		return "unknown"
	}
}
